### ISSUE TITLE
response_time_setting_count in OUTPUT_RESPONSE_TIME_DESCRIPTION and MODULATION_FREQUENCY_DESCRIPTION

### ISSUE THREAD

**Issue by Letrab** [ssilverman/rdm-schema#4]
Hi,

In the json description of `OUTPUT_RESPONSE_TIME_DESCRIPTION` and `MODULATION_FREQUENCY_DESCRIPTION` there is a GET parameter: `response_time_setting_count`

Is this a (copy/paste) error, as ANSI E1.37-1 – 2012 (R2017) does not mention an additional GET parameter, aside from the requested setting's number?

**Comment by peternewman** [comment]
Again I'd agree:
http://rdm.openlighting.org/pid/display?manufacturer=0&pid=838

And:
http://rdm.openlighting.org/pid/display?manufacturer=0&pid=840

Looks like a typo from `OUTPUT_RESPONSE_TIME` and `MODULATION_FREQUENCY`.

**Comment by Bartel-C8** [comment]
@ssilverman: What is your thought on this?

**Comment by Letrab** [comment]
@ssilverman: What is your thought on this?

**Comment by ssilverman** [comment]
You're right. Sorry to have missed the first notification; thanks for the ping. Fixed.
