### ISSUE TITLE
DNS_IPV4_NAMESERVER vs DNS_IPV4_NAME_SERVER

### ISSUE THREAD

**Issue by Letrab** [ssilverman/rdm-schema#5]
In ANSI E1.37-2 – 2015 `DNS_IPV4_NAME_SERVER` is used as name for getting a name server. In the json "name server" is written as one word, `DNS_IPV4_NAMESERVER`. It would be logical to follow the naming in the spec?

**Comment by peternewman** [comment]
OLA agrees with you and uses NAME_SERVER too FWIW:
http://rdm.openlighting.org/pid/display?manufacturer=0&pid=1803

**Comment by Bartel-C8** [comment]
@ssilverman: What is your thought on this?

**Comment by Letrab** [comment]
@ssilverman: What is your thought on this?

**Comment by ssilverman** [comment]
You're right. Sorry to have missed the first notification. Fixed.
